<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-search fa-2x mr-3"></i>
					Follow what suits you.
				</div>
				<div class="communicationItem">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Know what people are talking about.
				</div>
				<div class="communicationItem">
					<i class="far fa-comment fa-2x mr-3"></i>
					Be part of the conversation.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form>
			<div class="row">
				<div class="col">
					<input type="text" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="text" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Login</button>
				</div>
			</div>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="/img/twitter_logo.png" />
				<h1 class="title">See what is happening in the world right now!</h1>

				<h2 class="mt-5 subtitle">Join Twitter now.</h2>
				<a href="/register" class="btn btn-primary btn-block mb-2">Register</a>
			</div>	
		</div>


    </div>

  </div>
</div>