<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Create account</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/register_action" method="post">
              <div class="form-group">
                <input type="text" name="name" class="form-control" placeholder="Name">
              </div>
              
              <div class="form-group">
                <input type="text" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" name="pass" class="form-control" placeholder="Password">
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  On register you agree to the Twitter Terms of Service and Privacy Policy, including the use of cookies. Other people may find you by your e-mail address or registered phone number · Privacy Options
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Register</button>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  